// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/account.dart';
import 'data/models/category.dart';
import 'data/models/email_message.dart';
import 'data/models/index_progress.dart';
import 'data/models/job_application.dart';
import 'data/models/model_state.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6507495093653909782),
    name: 'Account',
    lastPropertyId: const obx_int.IdUid(9, 2693131121905883486),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7713444716302352523),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3707373721229314363),
        name: 'host',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7453575049870547823),
        name: 'port',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 319605615759901632),
        name: 'useSsl',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2583596430905942500),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8540835642450544588),
        name: 'credentialKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1179431218374317384),
        name: 'displayName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 747004187768072727),
        name: 'uidValidity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2693131121905883486),
        name: 'lastSyncAt',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7025095648086343076),
    name: 'Category',
    lastPropertyId: const obx_int.IdUid(5, 8259203914478303453),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2458881160140132177),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4491921300354564863),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7086671298104739915),
        name: 'colorHex',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6339403230564718130),
        name: 'targetFolder',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8259203914478303453),
        name: 'aiHint',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6908412378509859530),
    name: 'EmailMessage',
    lastPropertyId: const obx_int.IdUid(12, 3079782928366953464),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4931394781280464603),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3461767764870626419),
        name: 'uid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6758040801983812614),
        name: 'folder',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 612217562683478749),
        name: 'fromAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4148575708502135476),
        name: 'toAddresses',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5498968045446517187),
        name: 'subject',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7941510560655936729),
        name: 'bodyText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 534374194338849747),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5620361670419388534),
        name: 'isIndexed',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1202865763859886547),
        name: 'categoryId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6634688618490218403),
        name: 'embeddingModelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3079782928366953464),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(1, 8911551733343359280),
        hnswParams: obx_int.ModelHnswParams(dimensions: 384),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 4098448714851679179),
    name: 'IndexProgress',
    lastPropertyId: const obx_int.IdUid(6, 7741703861135436435),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3328873176100436182),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1914942888124970624),
        name: 'total',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 906087476363549006),
        name: 'done',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3780255704146744719),
        name: 'statusCode',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4277841283995540657),
        name: 'startedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7741703861135436435),
        name: 'modelId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 2334549536348639445),
    name: 'JobApplication',
    lastPropertyId: const obx_int.IdUid(7, 1854962457546798886),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7671590985668365547),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1255180725000601113),
        name: 'company',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 153215865258765714),
        name: 'appliedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3913592031456817709),
        name: 'statusCode',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7672538661690514202),
        name: 'emailId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2452727010164792424),
        name: 'manuallyEdited',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1854962457546798886),
        name: 'timelineJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 1403419918816672598),
    name: 'ModelState',
    lastPropertyId: const obx_int.IdUid(5, 6801680094712584457),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8105668347098969572),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9146711209196001519),
        name: 'currentModelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8685977219784441143),
        name: 'downloadedModelIds',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5235005242675299642),
        name: 'vectorDimensions',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6801680094712584457),
        name: 'useLocalModel',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 1403419918816672598),
    lastIndexId: const obx_int.IdUid(1, 8911551733343359280),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Account: obx_int.EntityDefinition<Account>(
      model: _entities[0],
      toOneRelations: (Account object) => [],
      toManyRelations: (Account object) => {},
      getId: (Account object) => object.id,
      setId: (Account object, int id) {
        object.id = id;
      },
      objectToFB: (Account object, fb.Builder fbb) {
        final hostOffset = fbb.writeString(object.host);
        final usernameOffset = fbb.writeString(object.username);
        final credentialKeyOffset = fbb.writeString(object.credentialKey);
        final displayNameOffset = fbb.writeString(object.displayName);
        final lastSyncAtOffset = object.lastSyncAt == null
            ? null
            : fbb.writeString(object.lastSyncAt!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, hostOffset);
        fbb.addInt64(2, object.port);
        fbb.addBool(3, object.useSsl);
        fbb.addOffset(4, usernameOffset);
        fbb.addOffset(5, credentialKeyOffset);
        fbb.addOffset(6, displayNameOffset);
        fbb.addInt64(7, object.uidValidity);
        fbb.addOffset(8, lastSyncAtOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Account()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..host = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..port = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
          ..useSsl = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            10,
            false,
          )
          ..username = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..credentialKey = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..displayName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..uidValidity = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..lastSyncAt = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 20);

        return object;
      },
    ),
    Category: obx_int.EntityDefinition<Category>(
      model: _entities[1],
      toOneRelations: (Category object) => [],
      toManyRelations: (Category object) => {},
      getId: (Category object) => object.id,
      setId: (Category object, int id) {
        object.id = id;
      },
      objectToFB: (Category object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final colorHexOffset = fbb.writeString(object.colorHex);
        final targetFolderOffset = fbb.writeString(object.targetFolder);
        final aiHintOffset = object.aiHint == null
            ? null
            : fbb.writeString(object.aiHint!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, colorHexOffset);
        fbb.addOffset(3, targetFolderOffset);
        fbb.addOffset(4, aiHintOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Category()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..colorHex = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..targetFolder = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..aiHint = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12);

        return object;
      },
    ),
    EmailMessage: obx_int.EntityDefinition<EmailMessage>(
      model: _entities[2],
      toOneRelations: (EmailMessage object) => [],
      toManyRelations: (EmailMessage object) => {},
      getId: (EmailMessage object) => object.id,
      setId: (EmailMessage object, int id) {
        object.id = id;
      },
      objectToFB: (EmailMessage object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final folderOffset = fbb.writeString(object.folder);
        final fromAddressOffset = fbb.writeString(object.fromAddress);
        final toAddressesOffset = fbb.writeString(object.toAddresses);
        final subjectOffset = fbb.writeString(object.subject);
        final bodyTextOffset = fbb.writeString(object.bodyText);
        final embeddingModelIdOffset = object.embeddingModelId == null
            ? null
            : fbb.writeString(object.embeddingModelId!);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, folderOffset);
        fbb.addOffset(3, fromAddressOffset);
        fbb.addOffset(4, toAddressesOffset);
        fbb.addOffset(5, subjectOffset);
        fbb.addOffset(6, bodyTextOffset);
        fbb.addInt64(7, object.date.millisecondsSinceEpoch);
        fbb.addBool(8, object.isIndexed);
        fbb.addInt64(9, object.categoryId);
        fbb.addOffset(10, embeddingModelIdOffset);
        fbb.addOffset(11, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = EmailMessage()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..uid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..folder = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..fromAddress = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..toAddresses = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..subject = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..bodyText = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..date = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
          )
          ..isIndexed = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            20,
            false,
          )
          ..categoryId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            22,
            0,
          )
          ..embeddingModelId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 24)
          ..embedding = const fb.ListReader<double>(
            fb.Float32Reader(),
            lazy: false,
          ).vTableGetNullable(buffer, rootOffset, 26);

        return object;
      },
    ),
    IndexProgress: obx_int.EntityDefinition<IndexProgress>(
      model: _entities[3],
      toOneRelations: (IndexProgress object) => [],
      toManyRelations: (IndexProgress object) => {},
      getId: (IndexProgress object) => object.id,
      setId: (IndexProgress object, int id) {
        object.id = id;
      },
      objectToFB: (IndexProgress object, fb.Builder fbb) {
        final modelIdOffset = fbb.writeString(object.modelId);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.total);
        fbb.addInt64(2, object.done);
        fbb.addInt64(3, object.statusCode);
        fbb.addInt64(4, object.startedAt.millisecondsSinceEpoch);
        fbb.addOffset(5, modelIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = IndexProgress()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..total = const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0)
          ..done = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
          ..statusCode = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..startedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
          )
          ..modelId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '');

        return object;
      },
    ),
    JobApplication: obx_int.EntityDefinition<JobApplication>(
      model: _entities[4],
      toOneRelations: (JobApplication object) => [],
      toManyRelations: (JobApplication object) => {},
      getId: (JobApplication object) => object.id,
      setId: (JobApplication object, int id) {
        object.id = id;
      },
      objectToFB: (JobApplication object, fb.Builder fbb) {
        final companyOffset = fbb.writeString(object.company);
        final timelineJsonOffset = fbb.writeString(object.timelineJson);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, companyOffset);
        fbb.addInt64(2, object.appliedAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.statusCode);
        fbb.addInt64(4, object.emailId);
        fbb.addBool(5, object.manuallyEdited);
        fbb.addOffset(6, timelineJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = JobApplication()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..company = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..appliedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          )
          ..statusCode = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..emailId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..manuallyEdited = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            14,
            false,
          )
          ..timelineJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '');

        return object;
      },
    ),
    ModelState: obx_int.EntityDefinition<ModelState>(
      model: _entities[5],
      toOneRelations: (ModelState object) => [],
      toManyRelations: (ModelState object) => {},
      getId: (ModelState object) => object.id,
      setId: (ModelState object, int id) {
        object.id = id;
      },
      objectToFB: (ModelState object, fb.Builder fbb) {
        final currentModelIdOffset = fbb.writeString(object.currentModelId);
        final downloadedModelIdsOffset = fbb.writeString(
          object.downloadedModelIds,
        );
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, currentModelIdOffset);
        fbb.addOffset(2, downloadedModelIdsOffset);
        fbb.addInt64(3, object.vectorDimensions);
        fbb.addBool(4, object.useLocalModel);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ModelState()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..currentModelId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..downloadedModelIds = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..vectorDimensions = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..useLocalModel = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            12,
            false,
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Account] entity fields to define ObjectBox queries.
class Account_ {
  /// See [Account.id].
  static final id = obx.QueryIntegerProperty<Account>(
    _entities[0].properties[0],
  );

  /// See [Account.host].
  static final host = obx.QueryStringProperty<Account>(
    _entities[0].properties[1],
  );

  /// See [Account.port].
  static final port = obx.QueryIntegerProperty<Account>(
    _entities[0].properties[2],
  );

  /// See [Account.useSsl].
  static final useSsl = obx.QueryBooleanProperty<Account>(
    _entities[0].properties[3],
  );

  /// See [Account.username].
  static final username = obx.QueryStringProperty<Account>(
    _entities[0].properties[4],
  );

  /// See [Account.credentialKey].
  static final credentialKey = obx.QueryStringProperty<Account>(
    _entities[0].properties[5],
  );

  /// See [Account.displayName].
  static final displayName = obx.QueryStringProperty<Account>(
    _entities[0].properties[6],
  );

  /// See [Account.uidValidity].
  static final uidValidity = obx.QueryIntegerProperty<Account>(
    _entities[0].properties[7],
  );

  /// See [Account.lastSyncAt].
  static final lastSyncAt = obx.QueryStringProperty<Account>(
    _entities[0].properties[8],
  );
}

/// [Category] entity fields to define ObjectBox queries.
class Category_ {
  /// See [Category.id].
  static final id = obx.QueryIntegerProperty<Category>(
    _entities[1].properties[0],
  );

  /// See [Category.name].
  static final name = obx.QueryStringProperty<Category>(
    _entities[1].properties[1],
  );

  /// See [Category.colorHex].
  static final colorHex = obx.QueryStringProperty<Category>(
    _entities[1].properties[2],
  );

  /// See [Category.targetFolder].
  static final targetFolder = obx.QueryStringProperty<Category>(
    _entities[1].properties[3],
  );

  /// See [Category.aiHint].
  static final aiHint = obx.QueryStringProperty<Category>(
    _entities[1].properties[4],
  );
}

/// [EmailMessage] entity fields to define ObjectBox queries.
class EmailMessage_ {
  /// See [EmailMessage.id].
  static final id = obx.QueryIntegerProperty<EmailMessage>(
    _entities[2].properties[0],
  );

  /// See [EmailMessage.uid].
  static final uid = obx.QueryStringProperty<EmailMessage>(
    _entities[2].properties[1],
  );

  /// See [EmailMessage.folder].
  static final folder = obx.QueryStringProperty<EmailMessage>(
    _entities[2].properties[2],
  );

  /// See [EmailMessage.fromAddress].
  static final fromAddress = obx.QueryStringProperty<EmailMessage>(
    _entities[2].properties[3],
  );

  /// See [EmailMessage.toAddresses].
  static final toAddresses = obx.QueryStringProperty<EmailMessage>(
    _entities[2].properties[4],
  );

  /// See [EmailMessage.subject].
  static final subject = obx.QueryStringProperty<EmailMessage>(
    _entities[2].properties[5],
  );

  /// See [EmailMessage.bodyText].
  static final bodyText = obx.QueryStringProperty<EmailMessage>(
    _entities[2].properties[6],
  );

  /// See [EmailMessage.date].
  static final date = obx.QueryDateProperty<EmailMessage>(
    _entities[2].properties[7],
  );

  /// See [EmailMessage.isIndexed].
  static final isIndexed = obx.QueryBooleanProperty<EmailMessage>(
    _entities[2].properties[8],
  );

  /// See [EmailMessage.categoryId].
  static final categoryId = obx.QueryIntegerProperty<EmailMessage>(
    _entities[2].properties[9],
  );

  /// See [EmailMessage.embeddingModelId].
  static final embeddingModelId = obx.QueryStringProperty<EmailMessage>(
    _entities[2].properties[10],
  );

  /// See [EmailMessage.embedding].
  static final embedding = obx.QueryHnswProperty<EmailMessage>(
    _entities[2].properties[11],
  );
}

/// [IndexProgress] entity fields to define ObjectBox queries.
class IndexProgress_ {
  /// See [IndexProgress.id].
  static final id = obx.QueryIntegerProperty<IndexProgress>(
    _entities[3].properties[0],
  );

  /// See [IndexProgress.total].
  static final total = obx.QueryIntegerProperty<IndexProgress>(
    _entities[3].properties[1],
  );

  /// See [IndexProgress.done].
  static final done = obx.QueryIntegerProperty<IndexProgress>(
    _entities[3].properties[2],
  );

  /// See [IndexProgress.statusCode].
  static final statusCode = obx.QueryIntegerProperty<IndexProgress>(
    _entities[3].properties[3],
  );

  /// See [IndexProgress.startedAt].
  static final startedAt = obx.QueryDateProperty<IndexProgress>(
    _entities[3].properties[4],
  );

  /// See [IndexProgress.modelId].
  static final modelId = obx.QueryStringProperty<IndexProgress>(
    _entities[3].properties[5],
  );
}

/// [JobApplication] entity fields to define ObjectBox queries.
class JobApplication_ {
  /// See [JobApplication.id].
  static final id = obx.QueryIntegerProperty<JobApplication>(
    _entities[4].properties[0],
  );

  /// See [JobApplication.company].
  static final company = obx.QueryStringProperty<JobApplication>(
    _entities[4].properties[1],
  );

  /// See [JobApplication.appliedAt].
  static final appliedAt = obx.QueryDateProperty<JobApplication>(
    _entities[4].properties[2],
  );

  /// See [JobApplication.statusCode].
  static final statusCode = obx.QueryIntegerProperty<JobApplication>(
    _entities[4].properties[3],
  );

  /// See [JobApplication.emailId].
  static final emailId = obx.QueryIntegerProperty<JobApplication>(
    _entities[4].properties[4],
  );

  /// See [JobApplication.manuallyEdited].
  static final manuallyEdited = obx.QueryBooleanProperty<JobApplication>(
    _entities[4].properties[5],
  );

  /// See [JobApplication.timelineJson].
  static final timelineJson = obx.QueryStringProperty<JobApplication>(
    _entities[4].properties[6],
  );
}

/// [ModelState] entity fields to define ObjectBox queries.
class ModelState_ {
  /// See [ModelState.id].
  static final id = obx.QueryIntegerProperty<ModelState>(
    _entities[5].properties[0],
  );

  /// See [ModelState.currentModelId].
  static final currentModelId = obx.QueryStringProperty<ModelState>(
    _entities[5].properties[1],
  );

  /// See [ModelState.downloadedModelIds].
  static final downloadedModelIds = obx.QueryStringProperty<ModelState>(
    _entities[5].properties[2],
  );

  /// See [ModelState.vectorDimensions].
  static final vectorDimensions = obx.QueryIntegerProperty<ModelState>(
    _entities[5].properties[3],
  );

  /// See [ModelState.useLocalModel].
  static final useLocalModel = obx.QueryBooleanProperty<ModelState>(
    _entities[5].properties[4],
  );
}
