import 'dart:io';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:objectbox/objectbox.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import '../../objectbox.g.dart'; // generated by build_runner
import '../models/account.dart';
import '../models/category.dart';
import '../models/email_message.dart';
import '../models/index_progress.dart';
import '../models/job_application.dart';
import '../models/model_state.dart';

/// Wraps the ObjectBox [Store] and exposes typed [Box] accessors.
class ObjectBoxStore {
  ObjectBoxStore._(this._store);

  final Store _store;

  static Future<ObjectBoxStore> create() async {
    final docsDir = await getApplicationDocumentsDirectory();
    final dbPath = p.join(docsDir.path, 'mail_agent_db');
    await Directory(dbPath).create(recursive: true);
    final store = await openStore(directory: dbPath);
    return ObjectBoxStore._(store);
  }

  Box<Account> get accounts => _store.box<Account>();
  Box<EmailMessage> get emails => _store.box<EmailMessage>();
  Box<Category> get categories => _store.box<Category>();
  Box<JobApplication> get jobApplications => _store.box<JobApplication>();
  Box<IndexProgress> get indexProgress => _store.box<IndexProgress>();
  Box<ModelState> get modelStates => _store.box<ModelState>();

  Store get store => _store;

  void close() => _store.close();
}

/// Riverpod provider — overridden at startup in main.dart after async init.
final objectBoxStoreProvider = Provider<ObjectBoxStore>((ref) {
  throw UnimplementedError('ObjectBoxStore must be initialized before use.');
});
